L8_2/discordbotdb/urls.py
from django.urls import include, path
from rest_framework import routers
from .views import (
    UsersListView,
    GuildsListView,
    StatusListView,
    HomeView,
    UserCreateView,
    UserUpdateView,
    UserDeleteView,
    GuildViewSet, UserViewSet, StatusViewSet, WeaponViewSet, GrenadeViewSet
)

router = routers.DefaultRouter()
router.register('guilds', GuildViewSet)
router.register('users', UserViewSet)
router.register('statuses', StatusViewSet)
router.register('weapons', WeaponViewSet)
router.register('grenades', GrenadeViewSet)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('api/', include(router.urls)),
    path('users/', UsersListView.as_view(), name='users'),
    path('guilds/', GuildsListView.as_view(), name='guilds'),
    path('status/<int:pk>/', StatusListView.as_view(), name='status'),
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
]

L8_2/task8/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('discordbotdb.urls')),
]

L8_2/discordbotdb/models.py
from django.db import models


class Guild(models.Model):
    guild_id = models.AutoField(primary_key=True)
    server_id = models.BigIntegerField()
    server_name = models.TextField()
    prefix = models.TextField(default='+')

    def __str__(self):
        return self.server_name


class User(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField()
    user_discord_id = models.BigIntegerField()
    guild = models.ForeignKey(Guild, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Status(models.Model):
    status_id = models.AutoField(primary_key=True)
    armour = models.CharField(max_length=255)
    head = models.IntegerField()
    body = models.IntegerField()
    l_hand = models.IntegerField()
    r_hand = models.IntegerField()
    l_foot = models.IntegerField()
    r_foot = models.IntegerField()
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Status for user {self.user.name}"


class Weapon(models.Model):
    weapon_id = models.AutoField(primary_key=True)
    weapon_name = models.TextField()
    current_ammo = models.IntegerField()
    inventory_name = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.weapon_name


class Grenade(models.Model):
    grenade_id = models.AutoField(primary_key=True)
    grenade_name = models.TextField()
    amount = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.grenade_name

L8_2/discordbotdb/forms.py
from django import forms
from django.core.validators import RegexValidator

from .models import User


class UserForm(forms.ModelForm):
    user_discord_id = forms.CharField(validators=[RegexValidator(r'^[0-9]{17,20}$', 'Введите допустимый Discord ID ('
                                                                                    'от 17 до 20 цифр).')])

    class Meta:
        model = User
        fields = ['name', 'user_discord_id', 'guild']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = True
        self.fields['name'].label = 'Имя пользователя'
        self.fields['user_discord_id'].required = True
        self.fields['user_discord_id'].label = 'Discord ID пользователя'
        self.fields['guild'].required = True
        self.fields['guild'].label = 'Сервер'

L8_2/discordbotdb/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, View, CreateView, UpdateView, DeleteView
from rest_framework import viewsets
from .forms import UserForm
from .models import User, Guild, Status, Weapon, Grenade
from .serializers import GuildSerializer, UserSerializer, StatusSerializer, WeaponSerializer, GrenadeSerializer


class HomeView(TemplateView):
    template_name = 'discordbotdb/home.html'


class UserCreateView(CreateView):
    model = User
    form_class = UserForm
    template_name = 'discordbotdb/user_create.html'
    success_url = reverse_lazy('users')


class UserUpdateView(UpdateView):
    model = User
    form_class = UserForm
    template_name = 'discordbotdb/user_update.html'
    success_url = reverse_lazy('users')


class UserDeleteView(DeleteView):
    model = User
    template_name = 'discordbotdb/user_delete.html'
    success_url = reverse_lazy('users')


class UsersListView(View):
    def get(self, request):
        search_query = request.GET.get('search', '')
        users = User.objects.filter(name__icontains=search_query)
        context = {'users': users, 'search_query': search_query}
        return render(request, 'discordbotdb/users_list.html', context)


class GuildsListView(ListView):
    model = Guild
    template_name = 'discordbotdb/guilds_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Список серверов'
        return context


class StatusListView(ListView):
    model = Status
    template_name = 'discordbotdb/status_list.html'
    context_object_name = 'status'

    def get_queryset(self):
        self.user_id = self.kwargs['pk']
        return Status.objects.filter(user_id=self.user_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Статус'
        context['user_id'] = self.user_id
        return context


class GuildViewSet(viewsets.ModelViewSet):
    queryset = Guild.objects.all()
    serializer_class = GuildSerializer

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class StatusViewSet(viewsets.ModelViewSet):
    queryset = Status.objects.all()
    serializer_class = StatusSerializer

class WeaponViewSet(viewsets.ModelViewSet):
    queryset = Weapon.objects.all()
    serializer_class = WeaponSerializer

class GrenadeViewSet(viewsets.ModelViewSet):
    queryset = Grenade.objects.all()
    serializer_class = GrenadeSerializer

L8_2/discordbotdb/templates/discordbotdb/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <title>{% block title %}Task8{% endblock %}</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Главная</a></li>
                <li><a href="{% url 'users' %}">Пользователи</a></li>
                <li><a href="{% url 'guilds' %}">Сервера</a></li>
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

L8_2/discordbotdb/templates/discordbotdb/guilds_list.html
{% extends 'discordbotdb/base.html' %}

{% block content %}
  <div class="server">
    <div class="server-container">
      <h1>Список серверов</h1>
      {% for guild in object_list %}
        <div class="server">
          <h2>{{ guild.server_name }}</h2>
          <div class="user-list">
            {% for user in guild.user_set.all %}
              <div class="user">
                <a class="user-link" href="{% url 'status' user.id %}">{{ user.name }}</a>
              </div>
            {% empty %}
              <div class="user">Пользователи не найдены.</div>
            {% endfor %}
          </div>
        </div>
      {% empty %}
        <p>Сервера не найдены.</p>
      {% endfor %}
    </div>
  </div>
{% endblock %}

L8_2/discordbotdb/templates/discordbotdb/home.html
{% extends 'discordbotdb/base.html' %}

{% block content %}
  <h1>Добро пожаловать на главную страницу</h1>
{% endblock %}

L8_2/discordbotdb/templates/discordbotdb/status_list.html
{% extends "discordbotdb/base.html" %}

{% block content %}
  <div class="status">
    {% for status in object_list %}
      <div class="status-container">
        <h1 class="status-username">{{ status.user.name }}</h1>

        <p class="status-server">{{ status.user.guild.server_name }}</p>

        <div class="status-body-parts-container">
          <h2>ХП частей тела</h2>
          <ul class="status-ul">
            <li>Голова: <span class="status-hp">{{ status.head }}</span></li>
            <li>Тело: <span class="status-hp">{{ status.body }}</span></li>
            <li>Левая рука: <span class="status-hp">{{ status.l_hand }}</span></li>
            <li>Правая рука: <span class="status-hp">{{ status.r_hand }}</span></li>
            <li>Левая нога: <span class="status-hp">{{ status.l_foot }}</span></li>
            <li>Правая нога: <span class="status-hp">{{ status.r_foot }}</span></li>
          </ul>
        </div>

        <div class="status-bottom-container">
          <div class="status-weapons-container">
            <h2>Оружие</h2>
            <ul class="status-ul">
              {% for weapon in status.user.weapon_set.all %}
                {% if weapon.inventory_name == "equipped" %}
                  <li>
                    <span class="status-equipped">{{ weapon.weapon_name|capfirst }}</span>
                    {% if weapon.current_ammo > 0 %}
                      <span class="status-equipped">(Количество патронов: {{ weapon.current_ammo }})</span>
                    {% endif %}
                  </li>
                {% else %}
                  <li>
                    {{ weapon.weapon_name|capfirst }}
                    {% if weapon.current_ammo > 0 %}
                      (Количество патронов: {{ weapon.current_ammo }})
                    {% endif %}
                  </li>
                {% endif %}
              {% empty %}
                <li>Нет оружия.</li>
              {% endfor %}
            </ul>
          </div>
          <div class="status-grenades-container">
            <h2>Гранаты</h2>
            <ul class="status-ul">
              {% for grenade in status.user.grenade_set.all %}
                <li>{{ grenade.grenade_name|capfirst }} (Количество: {{ grenade.amount }})</li>
              {% empty %}
                <li>Нет гранат.</li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    {% empty %}
      <p>У пользователя нет статуса.</p>
    {% endfor %}
  </div>
{% endblock %}

L8_2/discordbotdb/templates/discordbotdb/user_create.html
{% extends 'discordbotdb/base.html' %}

{% block content %}
  <h1>Создание пользователя</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Создать</button>
  </form>
{% endblock %}

L8_2/discordbotdb/templates/discordbotdb/user_delete.html
{% extends 'discordbotdb/base.html' %}

{% block content %}
  <h1>Удаление пользователя</h1>
  <p>Вы уверены, что хотите удалить пользователя "{{ object.name }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Удалить</button>
  </form>
{% endblock %}

L8_2/discordbotdb/templates/discordbotdb/user_update.html
{% extends 'discordbotdb/base.html' %}

{% block content %}
  <h1>Обновление пользователя</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Обновить</button>
  </form>
{% endblock %}

L8_2/discordbotdb/templates/discordbotdb/users_list.html
{% extends 'discordbotdb/base.html' %}

{% block styles %}
  {% load static %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'css/users.css' %}">
{% endblock %}

{% block content %}
  <div class="users">
    <div class="server-container">
      <h1>Список пользователей</h1>

      <div class="user-actions-left">
        <a href="{% url 'user_create' %}" class="user-action-button">Добавить</a>
      </div>

      <form method="GET" action="{% url 'users' %}">
        <input type="text" name="search" placeholder="Поиск по имени" value="{{ search_query }}" class="search-input">
        <button type="submit" class="search-button">Поиск</button>
      </form>

      {% if users %}
        <div class="user-list">
          {% for user in users %}
            <div class="user">
              <div class="user-info">
                <span class="user-id">{{ user.id }}.</span>
                <a href="{% url 'status' pk=user.id %}" class="user-link">
                  {{ user.name }}
                </a>
                <div class="user-details">
                  {{ user.guild.server_name }}
                </div>
              </div>
              <div class="user-actions-right">
                <a href="{% url 'user_update' pk=user.id %}" class="user-action-button">Обновить</a>
                <a href="{% url 'user_delete' pk=user.id %}" class="user-action-button">Удалить</a>
              </div>
            </div>
          {% endfor %}
        </div>
      {% else %}
        <p>Нет результатов</p>
      {% endif %}
    </div>
  </div>
{% endblock %}